### PR TITLE
Major rewrite of how migraiton graphs are defined

### PR DESCRIPTION
**Pull request by jmmshn**
Changing definition of MigrationGraph
- The old way was not super careful about how the object was defined
- The new way is much more care full about using the minimal set of information to construct the graph
- FullPathMapper has been renamed to MigrationGraph.
- A MigrationGraph only requires a structure that contains the sites and a structure graph that defines the sublattice migration.
- The ComputeEntryPath has been removed and all the code has been moved to various classmethods and functions that help construct a MigrationGraph.

Added some utils modules (open to input on the organization of this module):
parse_entries: takes collections of entries and groups them by structure similarity.
maggma: query functions for using maggma stores (this is useful for a very small set of people so I'm OK leaving it out)
~~get_migration_path: helper functions to help set up NEB calculations --- setting up the supercells~~

### CODE REVIEW

**Comment by shyuep** [comment]
Sorry, but there seems to be a conflict with existing code. Can you fix those pls? Thanks.

**Comment by jmmshn** [comment]
Sorry, this started as a completed PR but I realized late last week that a significant rewrite was needed to get this to a point where a database can be easily built and maintained.
I changed the text of the PR but forgot to change it to a WIP PR.
It is almost finished now though.  I will ping once it is complete

**Comment by jmmshn** [comment]
@shyuep  Ok I have removed the code that set up the NEB calculations since it makes more sense for them to be in another PR.

**Comment by shyuep** [comment]
Thanks.

**Pull request merged**
